import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "v1");
const output = join(root, "generated", "contracts.ts");
const names = {
  "engine_info.schema.json": "EngineInfo", "catalog_index.schema.json": "CatalogIndex",
  "cycle_editor_schema.schema.json": "CycleEditorSchema", "cycle_request.schema.json": "CycleRequest",
  "cycle_response.schema.json": "CycleResponse", "forever_request.schema.json": "ForeverRequest",
  "forever_response.schema.json": "ForeverResponse", "validation_report.schema.json": "ValidationReport",
  "engine_error.schema.json": "EngineError", "engine_warning.schema.json": "EngineWarning",
  "snapshot_envelope.schema.json": "SnapshotEnvelope",
};
const commonRefs = { metadata: "ContractMetadata", envelope: "ContractEnvelope", weight: "Weight", issue: "EngineIssue" };
const refName = (ref) => {
  const [file, fragment] = ref.split("#");
  if (basename(file) === "common.schema.json") return commonRefs[fragment.split("/").at(-1)] ?? "unknown";
  return names[basename(file)] ?? "unknown";
};
function typeOf(schema) {
  if (schema === true) return "unknown";
  if (schema.$ref) return refName(schema.$ref);
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map(JSON.stringify).join(" | ");
  if (schema.oneOf) return schema.oneOf.map(typeOf).join(" | ");
  if (Array.isArray(schema.type)) return schema.type.map((type) => typeOf({ type })).join(" | ");
  if (schema.type === "array") return `ReadonlyArray<${typeOf(schema.items ?? {})}>`;
  if (schema.type === "object" || schema.properties) {
    const required = new Set(schema.required ?? []);
    const fields = Object.entries(schema.properties ?? {}).map(([key, value]) => `readonly ${JSON.stringify(key)}${required.has(key) ? "" : "?"}: ${typeOf(value)};`);
    if (schema.additionalProperties && schema.additionalProperties !== false) fields.push(`readonly [key: string]: ${typeOf(schema.additionalProperties)};`);
    return `{ ${fields.join(" ")} }`;
  }
  if (schema.type === "string") return "string";
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "null") return "null";
  if (schema.allOf) return schema.allOf.map(typeOf).join(" & ");
  return "unknown";
}
const common = JSON.parse(await readFile(join(root, "common.schema.json"), "utf8"));
const declarations = Object.entries(commonRefs).map(([key, name]) => `export type ${name} = ${typeOf(common.$defs[key])};`);
for (const file of (await readdir(root)).filter((file) => names[file]).sort()) {
  declarations.push(`export type ${names[file]} = ${typeOf(JSON.parse(await readFile(join(root, file), "utf8")))};`);
}
await mkdir(dirname(output), { recursive: true });
await writeFile(output, `// Generated by contracts/generate-types.mjs. Do not edit.\n\n${declarations.join("\n\n")}\n`);
